#!/usr/bin/env bash
# ============================================================================
# WGCLOUD 全新部署快速指南 / Quick Start
# 
# 本文件是完整可部署的 Server 源码 + 编译产物包。
# 目标目录：/tmp/wg-server-full/（拷贝走这个目录即可在任何地方部署）
# ============================================================================
set -euo pipefail

echo "===================================================="
echo "  WGCLOUD v3.6.8 部署指南"
echo "  含：二开 AI + UFM + GPU + agent 防篡改 patch"
echo "===================================================="
echo ""
echo "本包位置: $(cd "$(dirname "$0")" && pwd)"
echo ""
echo "=== 目录结构 ==="
echo "  pom.xml                          Maven 构建文件"
echo "  src/                             源码"
echo "  target/wgcloud-server-release.jar  编译好的 jar（140M）"
echo "  sql/wgcloud-MySQL.sql            数据库建表脚本（可选）"
echo "  ai-config-snippet.yml            AI 配置片段"
echo ""
echo "=== 0) 前提 ==="
echo "  - Java 11+ 运行环境"
echo "  - MySQL 5.7+ / 8.0"
echo "  - Maven（如需重新编译）"
echo "  - Go agent（对应每台被监控主机）"
echo ""
echo "=== 1) 数据库初始化 ==="
echo "  mysql -u root -p < sql/wgcloud-MySQL.sql"
echo ""
echo "=== 2) 部署 Server ==="
echo "  mkdir -p /opt/wgcloud-server/config"
echo "  cp target/wgcloud-server-release.jar /opt/wgcloud-server/"
echo ""
echo "  # 配置 application.yml（关键字段）"
echo "  cat > /opt/wgcloud-server/config/application.yml << 'EOF'"
echo "  spring:"
echo "    datasource:"
echo "      url: jdbc:mysql://localhost:3306/wgcloud?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
echo "      username: root"
echo "      password: your_password"
echo "  server:"
echo "    port: 9999"
echo "  ai:"
echo "    enabled: yes"
echo "    baseUrl: http://192.168.157.200:82/v1"
echo "    apiKey: sk-qw3c0d3r-n3xt-9f8e7d6c5b4a3210"
echo "    model: DeepSeek-V4-Flash"
echo "  EOF"
echo ""
echo "  # 启动"
echo "  cd /opt/wgcloud-server"
echo "  nohup java -server -Xms512m -Xmx512m -jar wgcloud-server-release.jar --spring.config.location=config/application.yml > /dev/null 2>&1 &"
echo ""
echo "=== 3) 验证 ==="
echo "  curl http://127.0.0.1:9999/"
echo "  curl http://127.0.0.1:9999/ai/ping"
echo ""
echo "=== 4) Agent 部署 ==="
echo "  在每台被监控主机上："
echo "  tar xzf agent-linux-amd64-v3.6.8-patched.tar.gz"
echo "  cd agent-linux-amd64-v3.6.8"
echo "  # 修改 application.properties 中的 server 地址"
echo "  bash deploy.sh"
echo ""
echo "=== 5) 浏览器访问 ==="
echo "  http://<server-ip>:9999"
echo "  默认管理员：admin / admin"
echo ""
echo "  首次登录后在侧边栏查看："
echo "    - AI 智能分析 菜单（底部）"
echo "    - 主机详情页 → AI 诊断 按钮"
echo "    - 告警日志页 → AI 分析 按钮"
echo ""
echo "===================================================="
echo "  编译本包（如有源码修改）:"
echo "  cd $(cd "$(dirname "$0")" && pwd) && mvn clean package -DskipTests"
echo "===================================================="
