-- ============================================================
-- WGCLOUD v3.6.8 二次开发完整建表脚本 (2026-07-02)
-- 基于 60 个 MyBatis mapper XML 反推生成的完整表结构
-- 来源: /tmp/wg-server-full (0622 源码)
-- 说明: 全部使用 CREATE TABLE IF NOT EXISTS, 可重复执行安全
--       已存在表不会覆盖, 以下为缺列表追加 ALTER TABLE ADD COLUMN
-- ============================================================

-- ========================
-- 1. 官方 17 表已有, 但缺列的 ALTER 补丁放在最后
-- ========================

-- ========================
-- 2. 新表 (二次开发新增)
-- ========================

CREATE TABLE IF NOT EXISTS ACCOUNT_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWD VARCHAR(255),
    ACCOUNT_KEY VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    MENU_IDS TEXT,
    ACCOUNT_ROLE VARCHAR(255),
    ACCOUNT_PHONE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENT_RUN_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    ONLINE_TIME INT,
    DOWN_TIME INT,
    CREATE_TIME DATETIME,
    LAST_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APP_EXCEPTION_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    APP_PID VARCHAR(255),
    APP_NAME VARCHAR(255),
    CREATE_TIME DATETIME,
    CPU_PER DOUBLE,
    MEM_PER DOUBLE,
    APP_TYPE VARCHAR(255),
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    READ_BYTES VARCHAR(255),
    WRITES_BYTES VARCHAR(255),
    THREADS_NUM VARCHAR(255),
    GATHER_PID VARCHAR(255),
    GROUP_ID VARCHAR(50),
    APP_TIMES VARCHAR(255),
    PRO_USERNAME VARCHAR(255),
    CUSTOM_SHELL TEXT,
    WARN_LEVEL VARCHAR(255),
    NET_CONNECTIONS VARCHAR(255),
    APP_CMD_LINE TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CPU_TEMPERATURES (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    CORE_INDEX VARCHAR(255),
    CRIT VARCHAR(255),
    INPUT VARCHAR(255),
    MAX VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CUSTOM_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    CUSTOM_NAME VARCHAR(255),
    CUSTOM_SHELL TEXT,
    CREATE_TIME DATETIME,
    RESULT_EXP VARCHAR(255),
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    CUSTOM_VALUE VARCHAR(255),
    GROUP_ID VARCHAR(50),
    WARN_LEVEL VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CUSTOM_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    CUSTOM_INFO_ID VARCHAR(50),
    CUSTOM_VALUE VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DCE_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    RES_TIMES INT,
    ACTIVE VARCHAR(255),
    GROUP_ID VARCHAR(50),
    ACCOUNT VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    ORDER_NUM INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DCE_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    DCE_ID VARCHAR(50),
    RES_TIMES INT,
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DESK_IO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    FILE_STSTEM VARCHAR(255),
    CREATE_TIME DATETIME,
    READ_COUNT VARCHAR(255),
    WRITE_OUNT VARCHAR(255),
    READ_BYTES VARCHAR(255),
    WRITE_BYTES VARCHAR(255),
    READ_TIME VARCHAR(255),
    WRITE_TIME VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DISK_IO_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    READ_IO_AVG VARCHAR(255),
    WRITE_IO_AVG VARCHAR(255),
    CREATE_TIME DATETIME,
    READ_IO_COUNT_AVG VARCHAR(255),
    WRITE_IO_COUNT_AVG VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DISK_SMART (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    FILE_STSTEM VARCHAR(255),
    CREATE_TIME DATETIME,
    DISK_STATE VARCHAR(255),
    POWER_HOURS VARCHAR(255),
    POWER_COUNT VARCHAR(255),
    TEMPERATURE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DISK_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    FILE_STSTEM VARCHAR(255),
    DISK_SIZE VARCHAR(255),
    USED VARCHAR(255),
    AVAIL VARCHAR(255),
    USE_PER VARCHAR(255),
    DATE_STR VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOCKER_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    APP_TYPE VARCHAR(255),
    DOCKER_ID VARCHAR(255),
    DOCKER_NAME VARCHAR(255),
    CREATE_TIME DATETIME,
    DOCKER_STATE VARCHAR(255),
    USER_TIME VARCHAR(255),
    MEM_PER DOUBLE,
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    DOCKER_IMAGE VARCHAR(255),
    DOCKER_PORT VARCHAR(255),
    DOCKER_COMMAND VARCHAR(255),
    DOCKER_CREATED VARCHAR(255),
    DOCKER_SIZE VARCHAR(255),
    DOCKER_STATUS VARCHAR(255),
    GATHER_DOCKER_NAMES TEXT,
    GROUP_ID VARCHAR(50),
    WARN_LEVEL VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOCKER_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    DOCKER_INFO_ID VARCHAR(50),
    CPU_PER DOUBLE,
    MEM_PER DOUBLE,
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EQUIPMENT (
    ID VARCHAR(50) PRIMARY KEY,
    EQ_NAME VARCHAR(255),
    XINGHAO VARCHAR(255),
    PERSON VARCHAR(255),
    DEPT VARCHAR(255),
    CODE VARCHAR(255),
    PRICE DOUBLE,
    GONGYINGSHANG VARCHAR(255),
    CAIGOU_DATE DATETIME,
    REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    ACCOUNT VARCHAR(255),
    WEIBAO_DATE DATETIME,
    GROUP_ID VARCHAR(50),
    HOST_NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    FILE_PATH VARCHAR(255),
    FILE_SIZE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_SAFE (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    FILE_PATH VARCHAR(255),
    FILE_SIGN VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    FILE_MODTIME VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    GROUP_ID VARCHAR(50),
    FILE_IS_DIR VARCHAR(255),
    CUSTOM_SHELL TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_WARN (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    FILE_PATH VARCHAR(255),
    FILE_SIZE VARCHAR(255),
    CREATE_TIME DATETIME,
    WARN_CHARS VARCHAR(255),
    WARN_ROWS VARCHAR(255),
    REMARK VARCHAR(255),
    ACTIVE VARCHAR(255),
    FILE_NAME_PREFIX VARCHAR(255),
    FILE_TYPE VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    CUSTOM_SHELL TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_WARN_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    FILE_WARN_ID VARCHAR(50),
    FILE_PATH VARCHAR(255),
    WAR_CONTENT TEXT,
    CREATE_TIME DATETIME,
    ROWS_GATHER_COUNT VARCHAR(255),
    ROWS_COUNT VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FTP_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    FTP_HOST VARCHAR(255),
    USER_NAME VARCHAR(255),
    PASSWD VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    PORT VARCHAR(255),
    WARN_TYPE VARCHAR(255),
    ACCOUNT VARCHAR(255),
    FTP_NAME VARCHAR(255),
    RES_TIMES INT,
    FTP_TYPE VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    GROUP_ID VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GPU_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    GPU_RATE VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HEATH_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    HEATH_ID VARCHAR(50),
    RES_TIMES INT,
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_DISK_PER (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    DISK_SUM_PER DOUBLE,
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_GROUP (
    ID VARCHAR(50) PRIMARY KEY,
    GROUP_NAME VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    GROUP_TYPE VARCHAR(255),
    ACCOUNT VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_MAC_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    MAC_NAME VARCHAR(255),
    MAC_ADDRESS VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_PCI_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    DEVICE_ID VARCHAR(50),
    CREATE_TIME DATETIME,
    VENDOR_NAME VARCHAR(255),
    PRODUCT_NAME VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_USERS (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    HOST_USER VARCHAR(255),
    CREATE_TIME DATETIME,
    LAST_LOGIN_IP VARCHAR(255),
    LAST_LOGIN_TIME VARCHAR(255),
    TERMINAL VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_WARN_DIY (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    MEM_WARN_VAL DOUBLE,
    CPU_WARN_VAL DOUBLE,
    UPSPEED_VAL DOUBLE,
    UPSPEED_MIN_VAL DOUBLE,
    DOWNSPEED_VAL DOUBLE,
    DOWNSPEED_MIN_VAL DOUBLE,
    CPUTEMPERATURE_WARN_VAL DOUBLE,
    MEM_WARN_MAIL VARCHAR(255),
    UPSPEED_MAIL VARCHAR(255),
    DOWNSPEED_MAIL VARCHAR(255),
    CPU_WARN_MAIL VARCHAR(255),
    CPUTEMPERATURE_WARN_MAIL VARCHAR(255),
    DISK_WARN_MAIL VARCHAR(255),
    SMART_WARN_MAIL VARCHAR(255),
    DISK_BLOCK VARCHAR(255),
    DISK_WARN_VAL DOUBLE,
    SYSLOAD_WARN_MAIL VARCHAR(255),
    SYSLOAD_WARN_VAL DOUBLE,
    HOST_DOWN_WARN_MAIL VARCHAR(255),
    HOST_LOGIN_WARN_MAIL VARCHAR(255),
    CREATE_TIME DATETIME,
    ACCOUNT VARCHAR(255),
    ACTIVE VARCHAR(255),
    HOST_BLOCK_ALL_WARN VARCHAR(255),
    REMARK VARCHAR(255),
    SPEED_WARN_LEVEL VARCHAR(255),
    MEM_WARN_LEVEL VARCHAR(255),
    SYSLOAD_WARN_LEVEL VARCHAR(255),
    CPU_WARN_LEVEL VARCHAR(255),
    CPUTEMPERATURE_WARN_LEVEL VARCHAR(255),
    DISK_WARN_LEVEL VARCHAR(255),
    SMART_WARN_LEVEL VARCHAR(255),
    HOST_DOWN_WARN_LEVEL VARCHAR(255),
    HOST_LOGIN_WARN_LEVEL VARCHAR(255),
    NETCONNECTIONS_WARN_MAIL VARCHAR(255),
    NETCONNECTIONS_WARN_VAL DOUBLE,
    NETCONNECTIONS_WARN_LEVEL VARCHAR(255),
    DISK_BLOCK_SAVE VARCHAR(255),
    HOST_DOWN_WARN_COUNT VARCHAR(255),
    CUSTOM_WARN_MAIL VARCHAR(255),
    CUSTOM_WARN_ACCOUNT_KEY VARCHAR(255),
    DISKIO_SPEED_WARN_MAIL VARCHAR(255),
    DISKIO_SPEED_WARN_VAL DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS K8S_MONITOR (
    ID VARCHAR(50) PRIMARY KEY,
    DATA_TYPE VARCHAR(255),
    K8S_NAME VARCHAR(255),
    DATA_JSON TEXT,
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS KAFKA_MONITOR (
    ID VARCHAR(50) PRIMARY KEY,
    KAFKA_NAME VARCHAR(255),
    GROUP_ID VARCHAR(50),
    TOPIC_NAME VARCHAR(255),
    KAFKA_PARTITION VARCHAR(255),
    KAFKA_OFFSET VARCHAR(255),
    LAG_COUNT VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PASSWD_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    HOST_ACCOUNT VARCHAR(255),
    HOST_PASSWD VARCHAR(255),
    HOST_REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    ACCOUNT VARCHAR(255),
    GROUP_ID VARCHAR(50),
    HOST_MARK VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PORT_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    PORT VARCHAR(255),
    PORT_NAME VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    TELNET_IP VARCHAR(255),
    GROUP_ID VARCHAR(50),
    WARN_LEVEL VARCHAR(255),
    PORT_TYPE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REDIS_MONITOR (
    ID VARCHAR(50) PRIMARY KEY,
    REDIS_NAME VARCHAR(255),
    REDIS_VERSION VARCHAR(255),
    REDIS_MODE VARCHAR(255),
    PROCESS_ID VARCHAR(255),
    TCP_PORT VARCHAR(255),
    UPTIME_IN_DAYS VARCHAR(255),
    EXECUTABLE VARCHAR(255),
    CONFIG_FILE VARCHAR(255),
    CONNECTED_CLIENTS VARCHAR(255),
    BLOCKED_CLIENTS VARCHAR(255),
    USED_MEMORY_HUMAN VARCHAR(255),
    USED_MEMORY_PEAK_HUMAN VARCHAR(255),
    MAXMEMORY_HUMAN VARCHAR(255),
    AOF_ENABLED VARCHAR(255),
    RDB_LAST_BGSAVE_STATUS VARCHAR(255),
    RDB_LAST_BGSAVE_TIME_SEC VARCHAR(255),
    INSTANTANEOUS_OPS_PER_SEC VARCHAR(255),
    TOTAL_NET_INPUT_BYTES VARCHAR(255),
    TOTAL_NET_OUTPUT_BYTES VARCHAR(255),
    REJECTED_CONNECTIONS VARCHAR(255),
    REDIS_ROLE VARCHAR(255),
    CONNECTED_SLAVES VARCHAR(255),
    USED_CPU_SYS VARCHAR(255),
    EXPIRED_KEYS VARCHAR(255),
    EVICTED_KEYS VARCHAR(255),
    KEYSPACE_HITS VARCHAR(255),
    KEYSPACE_MISSES VARCHAR(255),
    PUBSUB_CHANNELS VARCHAR(255),
    PUBSUB_PATTERNS VARCHAR(255),
    CLUSTER_ENABLED VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255),
    REDIS_NODE_INFO TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REPORT_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    TIME_PART VARCHAR(255),
    REPORT_TYPE VARCHAR(255),
    CREATE_TIME DATETIME,
    GROUP_NAME VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REPORT_INSTANCE (
    ID VARCHAR(50) PRIMARY KEY,
    INFO_KEY VARCHAR(255),
    INFO_CONTENT TEXT,
    REPORT_INFO_ID VARCHAR(50),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHELL_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    SHELL TEXT,
    SHELL_NAME VARCHAR(255),
    STATE VARCHAR(255),
    CREATE_TIME DATETIME,
    SHELL_TYPE VARCHAR(255),
    SHELL_TIME VARCHAR(255),
    SHELL_DAY VARCHAR(255),
    ACCOUNT VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHELL_NOTE_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    SHELL_TITLE VARCHAR(255),
    SHELL_CONTENT TEXT,
    CREATE_TIME DATETIME,
    ACCOUNT VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHELL_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    SHELL_ID VARCHAR(50),
    SHELL TEXT,
    HOST_NAME VARCHAR(255),
    STATE VARCHAR(255),
    CREATE_TIME DATETIME,
    SHELL_TIME VARCHAR(255),
    SHELL_RESULT TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNMP_DEEP_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    CREATE_TIME DATETIME,
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    REMARK VARCHAR(255),
    SNMP_COMMUNITY VARCHAR(255),
    SNMP_PORT VARCHAR(255),
    SNMP_VERSION VARCHAR(255),
    ACCOUNT VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    GROUP_ID VARCHAR(50),
    SECURITY_NAME VARCHAR(255),
    AUTH_PASS VARCHAR(255),
    PRIV_PASS VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNMP_DEEP_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    SNMP_DEEP_INFO_ID VARCHAR(50),
    CREATE_TIME DATETIME,
    OID_VALUE VARCHAR(255),
    OID_TYPE VARCHAR(255),
    OID_NAME VARCHAR(255),
    OID_ORDER_NUM INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNMP_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    BYTES_RECV VARCHAR(255),
    BYTES_SENT VARCHAR(255),
    CREATE_TIME DATETIME,
    RECV_AVG VARCHAR(255),
    SENT_AVG VARCHAR(255),
    SNMP_UNIT VARCHAR(255),
    STATE VARCHAR(255),
    ACTIVE VARCHAR(255),
    REMARK VARCHAR(255),
    RECV_OID VARCHAR(255),
    SENT_OID VARCHAR(255),
    SNMP_COMMUNITY VARCHAR(255),
    SNMP_PORT VARCHAR(255),
    SNMP_VERSION VARCHAR(255),
    ACCOUNT VARCHAR(255),
    CPU_PER_OID VARCHAR(255),
    MEM_SIZE_OID VARCHAR(255),
    TEMPERATURE_OID VARCHAR(255),
    CPU_PER VARCHAR(255),
    MEM_PER VARCHAR(255),
    DISK_PER_OID VARCHAR(255),
    DISK_PER VARCHAR(255),
    SYS_DESC_VAL VARCHAR(255),
    SYS_DESC_OID VARCHAR(255),
    WARN_LEVEL VARCHAR(255),
    GROUP_ID VARCHAR(50),
    TEMPERATURE_VALUE VARCHAR(255),
    VOLTAGE_OID VARCHAR(255),
    VOLTAGE_VALUE VARCHAR(255),
    SECURITY_NAME VARCHAR(255),
    IFOPERSTATUS_OID VARCHAR(255),
    IFOPERSTATUS_VALUE VARCHAR(255),
    AUTH_PASS VARCHAR(255),
    PRIV_PASS VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNMP_STATE (
    ID VARCHAR(50) PRIMARY KEY,
    SNMP_INFO_ID VARCHAR(50),
    RECV_AVG VARCHAR(255),
    SENT_AVG VARCHAR(255),
    CREATE_TIME DATETIME,
    CPU_PER VARCHAR(255),
    MEM_PER VARCHAR(255),
    VOLTAGE_VALUE VARCHAR(255),
    TEMPERATURE_VALUE VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SYSTEM_INFO_EXT (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    PLATFORM VARCHAR(255),
    PLATFORM_VERSION VARCHAR(255),
    CPU_XH VARCHAR(255),
    UPTIME BIGINT,
    BOOT_TIME BIGINT,
    SUBMIT_SECONDS VARCHAR(255),
    AGENT_VER VARCHAR(255),
    CREATE_TIME DATETIME,
    BYTES_RECV VARCHAR(255),
    BYTES_SENT VARCHAR(255),
    HOST_NAME_EXT VARCHAR(255),
    SWAP_MEM_PER VARCHAR(255),
    TOTAL_SWAP_MEM VARCHAR(255),
    CPU_PHYSICALID VARCHAR(255),
    CPU_FAMILY VARCHAR(255),
    CPU_MHZ VARCHAR(255),
    KERNEL_ARCH VARCHAR(255),
    NET_INTERFACE_NAME VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TASK_JOB_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    HOST_NAME VARCHAR(255),
    CRON_VALUE VARCHAR(255),
    JOB_NAME VARCHAR(255),
    JOB_REMARK VARCHAR(255),
    CREATE_TIME DATETIME,
    ACCOUNT VARCHAR(255),
    ACTIVE VARCHAR(255),
    CALL_BACK_TIME DATETIME,
    GROUP_ID VARCHAR(50),
    CALL_BACK_STATE VARCHAR(255),
    SHELL TEXT,
    CALL_BACK_RESULT TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UFM_MONITOR (
    ID VARCHAR(50) PRIMARY KEY,
    GUID VARCHAR(255),
    SYSTEM_NAME VARCHAR(255),
    DEVICE_TYPE VARCHAR(255),
    DEVICE_STATE VARCHAR(255),
    SEVERITY VARCHAR(255),
    MB_OUT VARCHAR(255),
    MB_IN VARCHAR(255),
    PCK_OUT VARCHAR(255),
    PCK_IN VARCHAR(255),
    SYMBOL_ERRORS VARCHAR(255),
    LINK_RECOVERS VARCHAR(255),
    LINK_DOWNED VARCHAR(255),
    RCV_ERRORS VARCHAR(255),
    XMT_DISCARDS VARCHAR(255),
    MB_OUT_RATE VARCHAR(255),
    MB_IN_RATE VARCHAR(255),
    PCK_OUT_RATE VARCHAR(255),
    PCK_IN_RATE VARCHAR(255),
    ALARM_COUNT VARCHAR(255),
    CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ========================
-- 3. 官方 17 表缺列补丁 (ALTER TABLE ADD COLUMN IF NOT EXISTS)
--    这些表已存在但缺列, 补全缺的列
-- ========================

-- CPU_STATE: 缺 PROCS_NUM
ALTER TABLE CPU_STATE ADD COLUMN IF NOT EXISTS PROCS_NUM INT AFTER SYS;

-- NETIO_STATE: 缺 DROPIN, DROPOUT, NET_CONNECTIONS
ALTER TABLE NETIO_STATE ADD COLUMN IF NOT EXISTS DROPIN VARCHAR(255) AFTER TXBYT;
ALTER TABLE NETIO_STATE ADD COLUMN IF NOT EXISTS DROPOUT VARCHAR(255) AFTER DROPIN;
ALTER TABLE NETIO_STATE ADD COLUMN IF NOT EXISTS NET_CONNECTIONS VARCHAR(255) AFTER DROPOUT;

-- SYSTEM_INFO: 缺 GROUP_ID, PROCS, TOTAL_MEM, RXBYT, TXBYT, WIN_CONSOLE,
--              FIVE_LOAD, FIFTEEN_LOAD, NET_CONNECTIONS, ACCOUNT, ACTIVE,
--              COUNT_BLOCK, ORDER_NUM, DISK_PER, DISK_SUM_SIZE
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS GROUP_ID VARCHAR(50) AFTER REMARK;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS PROCS VARCHAR(255) AFTER GROUP_ID;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS TOTAL_MEM VARCHAR(255) AFTER PROCS;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS RXBYT VARCHAR(255) AFTER TOTAL_MEM;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS TXBYT VARCHAR(255) AFTER RXBYT;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS WIN_CONSOLE VARCHAR(255) AFTER TXBYT;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS FIVE_LOAD DOUBLE AFTER WIN_CONSOLE;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS FIFTEEN_LOAD DOUBLE AFTER FIVE_LOAD;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS NET_CONNECTIONS VARCHAR(255) AFTER FIFTEEN_LOAD;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS ACCOUNT VARCHAR(255) AFTER NET_CONNECTIONS;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER ACCOUNT;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS COUNT_BLOCK VARCHAR(255) AFTER ACTIVE;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS ORDER_NUM INT AFTER COUNT_BLOCK;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS DISK_PER DOUBLE AFTER ORDER_NUM;
ALTER TABLE SYSTEM_INFO ADD COLUMN IF NOT EXISTS DISK_SUM_SIZE VARCHAR(255) AFTER DISK_PER;

-- HEATH_MONITOR: 缺 RES_TIMES, ACTIVE, RES_KEYWORD, RES_NO_KEYWORD, METHOD, POST_STR,
--                HEADER_JSON, ACCOUNT, RESPONSE_BODY_SIZE, FORM_JSON, ERROR_MSG, WARN_LEVEL, GROUP_ID
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS RES_TIMES INT AFTER HEATH_STATUS;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER RES_TIMES;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS RES_KEYWORD VARCHAR(255) AFTER ACTIVE;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS RES_NO_KEYWORD VARCHAR(255) AFTER RES_KEYWORD;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS METHOD VARCHAR(255) AFTER RES_NO_KEYWORD;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS POST_STR TEXT AFTER METHOD;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS HEADER_JSON TEXT AFTER POST_STR;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS ACCOUNT VARCHAR(255) AFTER HEADER_JSON;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS RESPONSE_BODY_SIZE VARCHAR(255) AFTER ACCOUNT;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS FORM_JSON TEXT AFTER RESPONSE_BODY_SIZE;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS ERROR_MSG TEXT AFTER FORM_JSON;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS WARN_LEVEL VARCHAR(255) AFTER ERROR_MSG;
ALTER TABLE HEATH_MONITOR ADD COLUMN IF NOT EXISTS GROUP_ID VARCHAR(50) AFTER WARN_LEVEL;

-- APP_INFO: 缺 ACTIVE, READ_BYTES, WRITES_BYTES, THREADS_NUM, GATHER_PID,
--           GROUP_ID, APP_TIMES, PRO_USERNAME, CUSTOM_SHELL, WARN_LEVEL, NET_CONNECTIONS, APP_CMD_LINE
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER STATE;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS READ_BYTES VARCHAR(255) AFTER ACTIVE;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS WRITES_BYTES VARCHAR(255) AFTER READ_BYTES;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS THREADS_NUM VARCHAR(255) AFTER WRITES_BYTES;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS GATHER_PID VARCHAR(255) AFTER THREADS_NUM;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS GROUP_ID VARCHAR(50) AFTER GATHER_PID;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS APP_TIMES VARCHAR(255) AFTER GROUP_ID;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS PRO_USERNAME VARCHAR(255) AFTER APP_TIMES;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS CUSTOM_SHELL TEXT AFTER PRO_USERNAME;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS WARN_LEVEL VARCHAR(255) AFTER CUSTOM_SHELL;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS NET_CONNECTIONS VARCHAR(255) AFTER WARN_LEVEL;
ALTER TABLE APP_INFO ADD COLUMN IF NOT EXISTS APP_CMD_LINE TEXT AFTER NET_CONNECTIONS;

-- APP_STATE: 缺 THREADS_NUM, NET_CONNECTIONS
ALTER TABLE APP_STATE ADD COLUMN IF NOT EXISTS THREADS_NUM VARCHAR(255) AFTER MEM_PER;
ALTER TABLE APP_STATE ADD COLUMN IF NOT EXISTS NET_CONNECTIONS VARCHAR(255) AFTER THREADS_NUM;

-- DB_INFO: 缺 USER_NAME, DBURL, ACCOUNT, WARN_LEVEL, DRIVER_NAME, TEST_QUERY_SQL, ACTIVE, GROUP_ID, RES_TIMES
--          注意: 官方脚本列名是 USER/IP/PORT/DBNAME, 代码用 USER_NAME/DBURL
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS USER_NAME VARCHAR(255) AFTER DBTYPE;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS DBURL VARCHAR(255) AFTER PASSWD;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS ACCOUNT VARCHAR(255) AFTER DB_STATE;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS WARN_LEVEL VARCHAR(255) AFTER ACCOUNT;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS DRIVER_NAME VARCHAR(255) AFTER WARN_LEVEL;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS TEST_QUERY_SQL VARCHAR(255) AFTER DRIVER_NAME;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER TEST_QUERY_SQL;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS GROUP_ID VARCHAR(50) AFTER ACTIVE;
ALTER TABLE DB_INFO ADD COLUMN IF NOT EXISTS RES_TIMES INT AFTER GROUP_ID;

-- DB_TABLE: 缺 ACTIVE, RESULT_EXP, STATE, WARN_LEVEL, REMARK_EXT, RES_TIMES
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER TABLE_COUNT;
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS RESULT_EXP VARCHAR(255) AFTER ACTIVE;
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS STATE VARCHAR(255) AFTER RESULT_EXP;
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS WARN_LEVEL VARCHAR(255) AFTER STATE;
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS REMARK_EXT VARCHAR(255) AFTER WARN_LEVEL;
ALTER TABLE DB_TABLE ADD COLUMN IF NOT EXISTS RES_TIMES INT AFTER REMARK_EXT;

-- MAIL_SET: 缺 ACTIVE, JAVAX_MAIL
ALTER TABLE MAIL_SET ADD COLUMN IF NOT EXISTS ACTIVE VARCHAR(255) AFTER SMTP_SSL;
ALTER TABLE MAIL_SET ADD COLUMN IF NOT EXISTS JAVAX_MAIL VARCHAR(255) AFTER ACTIVE;

-- MEM_STATE: 添加代码可能用到的 TOTAL, USED, FREE (代码 insert 仅用 HOST_NAME/USE_PER,
--            但 tableColumnList/select 可能也用全部, 补上冗余列)
-- 实际上代码 MEM_STATE 的 insert 只需要 ID/HOST_NAME/USE_PER/CREATE_TIME,
-- 原脚本已有 TOTAL/USED/FREE/DATE_STR, 无需补.

-- SYS_LOAD_STATE / TCP_STATE / LOG_INFO / INTRUSION_INFO: 无缺列

-- HOST_INFO: 代码未直接使用其 mapper (无法从 mapper 反推列), 保持原脚本状态

-- DESK_STATE: 与代码的 DISK_STATE 是不同表 (DESK vs DISK), 保持不动

-- ========================
-- 4. 补完全部 DDL
-- ========================

-- APP_INFO/APP_STATE/CPU_STATE/DB_INFO/DB_TABLE/DB_TABLE_COUNT/HEATH_MONITOR/
-- HOST_INFO/INTRUSION_INFO/LOG_INFO/MAIL_SET/MEM_STATE/NETIO_STATE/
-- SYSTEM_INFO/SYS_LOAD_STATE/TCP_STATE 这些官方 17 表已有定义(row_format=compact),
-- 上面已给出 ALTER 补列, 无需重复 CREATE.

-- ========================
-- 5. 索引 (可选优化, 代码 mapper 中 WHERE 条件常用)
-- ========================
-- 可以根据实际查询模式添加索引, 但非必需. 建议后续按需添加.
